services:
  db:
    image: postgres:14
    env_file:
      - ./Api/.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    stop_grace_period: 10s
    security_opt:
      - apparmor=unconfined
    networks:
      - admin-panel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile.dev
    env_file:
      - ./Api/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '5210:5210'
    restart: unless-stopped
    stop_grace_period: 10s
    security_opt:
      - apparmor=unconfined
    networks:
      - admin-panel-network
    volumes:
      - ./Api:/app
      - /app/obj      # Evita conflito com build local
      - /app/bin      # Evita conflito com build local

  webapp:
    build:
      context: ./WebApp
      dockerfile: Dockerfile    # Usando o Dockerfile existente
    depends_on:
      - api
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE_URL=http://localhost:5210/api
    restart: unless-stopped
    stop_grace_period: 10s
    security_opt:
      - apparmor=unconfined
    networks:
      - admin-panel-network
    volumes:
      - ./WebApp:/app
      - /app/node_modules   # IMPORTANTE: preserva node_modules do container

networks:
  admin-panel-network:
    driver: bridge

volumes:
  pgdata:
