// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260829213142_AddDispatches")]
    partial class AddDispatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.AIAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<int>("OccurrenceId")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("RecommendedPriority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("recommended_priority");

                    b.Property<string>("RecommendedType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("recommended_type");

                    b.Property<bool>("RecommendsFireDepartment")
                        .HasColumnType("boolean")
                        .HasColumnName("recommends_fire_department");

                    b.Property<bool>("RecommendsPolice")
                        .HasColumnType("boolean")
                        .HasColumnName("recommends_police");

                    b.Property<bool>("RecommendsSamu")
                        .HasColumnType("boolean")
                        .HasColumnName("recommends_samu");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OccurrenceId", "CreatedAt")
                        .HasDatabaseName("ix_ai_analyses_occurrence_id_created_at");

                    b.ToTable("ai_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_analyses_recommended_priority", "recommended_priority IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')");

                            t.HasCheckConstraint("ck_ai_analyses_recommended_type", "recommended_type IN ('ACIDENTE_TRANSITO', 'INCENDIO', 'AGRESSAO', 'ROUBO', 'FERIMENTO', 'MAL_SUBITO', 'PESSOA_DESAPARECIDA', 'RESGATE', 'OUTROS')");

                            t.HasCheckConstraint("ck_ai_analyses_services", "recommends_police OR recommends_samu OR recommends_fire_department");
                        });
                });

            modelBuilder.Entity("Api.Models.AccessPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SystemResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("system_resource_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SystemResourceId");

                    b.HasIndex("UserId", "SystemResourceId")
                        .IsUnique()
                        .HasDatabaseName("ux_access_permissions_user_resource");

                    b.ToTable("access_permissions", (string)null);
                });

            modelBuilder.Entity("Api.Models.Dispatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfirmedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OccurrenceId")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_id");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByUserId")
                        .HasDatabaseName("ix_dispatches_confirmed_by_user_id");

                    b.HasIndex("OccurrenceId", "CreatedAt")
                        .HasDatabaseName("ix_dispatches_occurrence_created_at");

                    b.HasIndex("OccurrenceId", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("ux_dispatches_occurrence_unit");

                    b.HasIndex("UnitId", "CreatedAt")
                        .HasDatabaseName("ix_dispatches_unit_created_at");

                    b.ToTable("dispatches", (string)null);
                });

            modelBuilder.Entity("Api.Models.EmergencyService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("EmergencyNumber")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("emergency_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmergencyNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_emergency_services_number");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("ux_emergency_services_type");

                    b.ToTable("emergency_services", null, t =>
                        {
                            t.HasCheckConstraint("ck_emergency_services_mapping", "(type = 'POLICIA' AND emergency_number = '190') OR (type = 'SAMU' AND emergency_number = '192') OR (type = 'BOMBEIROS' AND emergency_number = '193')");

                            t.HasCheckConstraint("ck_emergency_services_number", "emergency_number IN ('190', '192', '193')");

                            t.HasCheckConstraint("ck_emergency_services_type", "type IN ('POLICIA', 'SAMU', 'BOMBEIROS')");
                        });
                });

            modelBuilder.Entity("Api.Models.Occurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmedPriority")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("confirmed_priority");

                    b.Property<string>("ConfirmedType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("confirmed_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("FireDepartmentConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fire_department_confirmed");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_description");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<bool>("PoliceConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("police_confirmed");

                    b.Property<bool>("SamuConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("samu_confirmed");

                    b.Property<DateTime?>("ServicesConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("services_confirmed_at");

                    b.Property<int?>("ServicesConfirmedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("services_confirmed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("ABERTA")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ServicesConfirmedByUserId");

                    b.HasIndex("CreatedByUserId", "CreatedAt")
                        .HasDatabaseName("ix_occurrences_created_by_user_id_created_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_occurrences_status_created_at");

                    b.ToTable("occurrences", null, t =>
                        {
                            t.HasCheckConstraint("ck_occurrences_confirmed_priority", "confirmed_priority IS NULL OR confirmed_priority IN ('BAIXA', 'MEDIA', 'ALTA', 'CRITICA')");

                            t.HasCheckConstraint("ck_occurrences_confirmed_type", "confirmed_type IS NULL OR confirmed_type IN ('ACIDENTE_TRANSITO', 'INCENDIO', 'AGRESSAO', 'ROUBO', 'FERIMENTO', 'MAL_SUBITO', 'PESSOA_DESAPARECIDA', 'RESGATE', 'OUTROS')");

                            t.HasCheckConstraint("ck_occurrences_latitude", "latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_occurrences_longitude", "longitude BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_occurrences_service_confirmation", "(services_confirmed_by_user_id IS NULL AND services_confirmed_at IS NULL AND NOT police_confirmed AND NOT samu_confirmed AND NOT fire_department_confirmed) OR (services_confirmed_by_user_id IS NOT NULL AND services_confirmed_at IS NOT NULL AND (police_confirmed OR samu_confirmed OR fire_department_confirmed))");

                            t.HasCheckConstraint("ck_occurrences_status", "status IN ('ABERTA', 'EM_ANALISE', 'AGUARDANDO_CONFIRMACAO', 'DESPACHADA', 'EM_ATENDIMENTO', 'FINALIZADA', 'CANCELADA')");
                        });
                });

            modelBuilder.Entity("Api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Api.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("generated_by");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_system_logs_user_id");

                    b.ToTable("system_logs", (string)null);
                });

            modelBuilder.Entity("Api.Models.SystemResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExhibitionName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("exhibition_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_system_resources_name");

                    b.ToTable("system_resources", (string)null);
                });

            modelBuilder.Entity("Api.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmergencyServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("emergency_service_id");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("DISPONIVEL")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_units_normalized_name");

                    b.HasIndex("EmergencyServiceId", "Status")
                        .HasDatabaseName("ix_units_service_status");

                    b.ToTable("units", null, t =>
                        {
                            t.HasCheckConstraint("ck_units_latitude", "latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_units_longitude", "longitude BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_units_status", "status IN ('DISPONIVEL', 'DESLOCAMENTO', 'EM_ATENDIMENTO', 'INDISPONIVEL')");
                        });
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Api.Models.AIAnalysis", b =>
                {
                    b.HasOne("Api.Models.Occurrence", "Occurrence")
                        .WithMany("AIAnalyses")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Occurrence");
                });

            modelBuilder.Entity("Api.Models.AccessPermission", b =>
                {
                    b.HasOne("Api.Models.SystemResource", "SystemResource")
                        .WithMany("AccessPermissions")
                        .HasForeignKey("SystemResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Models.User", "User")
                        .WithMany("AccessPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SystemResource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.Dispatch", b =>
                {
                    b.HasOne("Api.Models.User", "ConfirmedByUser")
                        .WithMany("ConfirmedDispatches")
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Models.Occurrence", "Occurrence")
                        .WithMany("Dispatches")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Models.Unit", "Unit")
                        .WithMany("Dispatches")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("Occurrence");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Api.Models.Occurrence", b =>
                {
                    b.HasOne("Api.Models.User", "CreatedByUser")
                        .WithMany("Occurrences")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Models.User", "ServicesConfirmedByUser")
                        .WithMany("ConfirmedServiceOccurrences")
                        .HasForeignKey("ServicesConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServicesConfirmedByUser");
                });

            modelBuilder.Entity("Api.Models.RefreshToken", b =>
                {
                    b.HasOne("Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.SystemLog", b =>
                {
                    b.HasOne("Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.Unit", b =>
                {
                    b.HasOne("Api.Models.EmergencyService", "EmergencyService")
                        .WithMany("Units")
                        .HasForeignKey("EmergencyServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmergencyService");
                });

            modelBuilder.Entity("Api.Models.EmergencyService", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Api.Models.Occurrence", b =>
                {
                    b.Navigation("AIAnalyses");

                    b.Navigation("Dispatches");
                });

            modelBuilder.Entity("Api.Models.SystemResource", b =>
                {
                    b.Navigation("AccessPermissions");
                });

            modelBuilder.Entity("Api.Models.Unit", b =>
                {
                    b.Navigation("Dispatches");
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Navigation("AccessPermissions");

                    b.Navigation("ConfirmedDispatches");

                    b.Navigation("ConfirmedServiceOccurrences");

                    b.Navigation("Occurrences");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
