import { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Card, CardActions, CardContent, Chip, Container, Stack, Tab, Tabs, Typography } from '@mui/material';
import type { Hospital, HospitalWard, PatientTransport } from '../../interfaces';
import { actOnReception, getMyHospital, listHospitalReceptions, updateMyHospitalWard } from '../../services';
import { createDispatchConnection } from '../../services/dispatchRealtimeService';
import { getErrorMessage } from '../../helpers';

export default function HospitalReceptions() {
  const [scope, setScope] = useState<'active' | 'history'>('active'); const [items, setItems] = useState<PatientTransport[]>([]); const [error, setError] = useState('');
  const [hospital, setHospital] = useState<Hospital | null>(null);
  const load = useCallback(async () => { try { const [receptions, currentHospital] = await Promise.all([listHospitalReceptions(scope), getMyHospital()]); setItems(receptions); setHospital(currentHospital); setError(''); } catch (e) { setError(getErrorMessage(e)); } }, [scope]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const connection = createDispatchConnection(() => void load(), () => void load(), () => void load()); void connection.start().catch(() => undefined); return () => { void connection.stop(); }; }, [load]);
  const act = async (item: PatientTransport, action: 'CIENCIA' | 'RECEBIDO' | 'CANCELADO') => { try { await actOnReception(item, action); await load(); } catch (e) { setError(getErrorMessage(e)); } };
  const capacity = async (ward: HospitalWard) => { const occupied = Number(window.prompt(`Vagas ocupadas em ${ward.name}:`, String(ward.occupiedBeds))); if (!Number.isInteger(occupied)) return; try { await updateMyHospitalWard({ ...ward, occupiedBeds: occupied }); await load(); } catch (e) { setError(getErrorMessage(e)); } };
  return <Container maxWidth="lg" sx={{ py: 3 }}><Typography variant="h4">Recebimentos</Typography><Typography color="text.secondary">{hospital?.name ?? 'Pacientes encaminhados ao hospital.'}</Typography>{hospital && <Card variant="outlined" sx={{ mt: 2 }}><CardContent><Typography variant="h6">Capacidade das alas</Typography><Stack direction={{ xs: 'column', md: 'row' }} gap={1} mt={1}>{hospital.wards.map(w => <Button key={w.id} variant="outlined" onClick={() => void capacity(w)}>{w.name}: {w.availableBeds} livres, {w.reservedBeds} reservadas</Button>)}</Stack></CardContent></Card>}<Tabs value={scope} onChange={(_, value) => setScope(value)}><Tab value="active" label="Ativos" /><Tab value="history" label="Histórico" /></Tabs>{error && <Alert severity="error" sx={{ my: 2 }}>{error}</Alert>}<Stack gap={2} mt={2}>{items.map(item => <Card key={item.id} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between"><Typography variant="h6">Ocorrência #{item.occurrenceId}</Typography><Chip label={item.status.replaceAll('_', ' ')} /></Stack><Typography fontWeight={600}>{item.priority?.replaceAll('_', ' ') ?? 'Sem prioridade'} · {item.type?.replaceAll('_', ' ') ?? 'Sem tipo'}</Typography><Typography>{item.description}</Typography><Typography color="text.secondary">Origem: {item.origin}</Typography><Typography>Ala: {item.wardName}</Typography>{item.operationalNotes && <Alert severity="info" sx={{ mt: 1 }}>{item.operationalNotes}</Alert>}</CardContent><CardActions>{!item.acknowledgedAt && item.status === 'HOSPITAL_AVISADO' && <Button variant="contained" onClick={() => void act(item, 'CIENCIA')}>Confirmar ciência</Button>}{['HOSPITAL_AVISADO', 'EM_TRANSPORTE'].includes(item.status) && <Button color="success" onClick={() => void act(item, 'RECEBIDO')}>Registrar chegada</Button>}{!['RECEBIDO', 'CANCELADO'].includes(item.status) && <Button color="error" onClick={() => void act(item, 'CANCELADO')}>Cancelar recebimento</Button>}</CardActions></Card>)}</Stack>{items.length === 0 && <Alert severity="info" sx={{ mt: 2 }}>Nenhum recebimento nesta lista.</Alert>}</Container>;
}
